### ISSUE TITLE
help!!!

### ISSUE THREAD

**Issue by LucasLiraDeOliveira** [bituco/ex6b-grupo3#3]
comecei a fazer as dicas mas tem certas partes que precisamos entender como fazer

**Comment by bituco** [comment]
A gente vai tentar continuar de onde tu parou. Qualquer coisa quando tu chegar em casa entra no skype e a gente termina

**Comment by LucasLiraDeOliveira** [comment]
pronto, vou tentar tirar minhas (muitas kkkk) dúvidas com hugo pra melhorar

**Comment by dmfds** [comment]
Boa tarde, pessoal na minha concepção temos que reduzir a quantidade de das combinações de cada dica. A começar pela dica 1.
